# Generated by Django 3.2.13 on 2022-10-27 10:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='group',
            field=models.CharField(choices=[('student', '학생'), ('teacher', '강사')], default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
